#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMColorResult
@end

@interface CMColorResult : CMObject

/* Red (R) channel pixel value of this color [optional]
 */
@property(nonatomic) NSNumber* R;
/* Green (G) channel pixel value of this color [optional]
 */
@property(nonatomic) NSNumber* G;
/* Blue (B) channel pixel value of this color [optional]
 */
@property(nonatomic) NSNumber* B;

@end
