#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMCreateHandwritingRequest
@end

@interface CMCreateHandwritingRequest : CMObject

/* Text to convert to handwriting [optional]
 */
@property(nonatomic) NSString* textInput;
/* Desired width in pixels of the resulting image [optional]
 */
@property(nonatomic) NSNumber* targetWidth;
/* Optinoal; Width of the text stroke in pixels; default is 2 [optional]
 */
@property(nonatomic) NSNumber* strokeWidth;
/* HTML hexadecimal color, or HTML common color name (e.g. 'black', 'red'), for the handwriting [optional]
 */
@property(nonatomic) NSString* color;

@end
