#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDetectedLicensePlate
@end

@interface CMDetectedLicensePlate : CMObject


@property(nonatomic) NSNumber* locationX;

@property(nonatomic) NSNumber* locationY;

@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;
/* Text from the license plate, highest-confidence result [optional]
 */
@property(nonatomic) NSString* licensePlateTextBestMatch;
/* Alternate text from the license plate, based on second-highest-confidence result [optional]
 */
@property(nonatomic) NSString* licensePlateTextRunnerUp;
/* Confidence score on a range of 0.0 - 1.0 of the accuracy of the detected license plate, with higher scores being better; values about 0.75 are high confidence [optional]
 */
@property(nonatomic) NSNumber* licensePlateRecognitionConfidenceLevel;

@end
