#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDetectedLicensePlate
@end

@interface CMDetectedLicensePlate : CMObject

/* Text from the license plate, highest-confidence result [optional]
 */
@property(nonatomic) NSString* licensePlateTextBestMatch;
/* Alternate text from the license plate, based on second-highest-confidence result [optional]
 */
@property(nonatomic) NSString* licensePlateTextRunnerUp;
/* X location of the left edge of the license plate, starting from the left edge of the photo (X = 0) [optional]
 */
@property(nonatomic) NSNumber* locationX;
/* Y location of the top edge of the license plate, starting from the top edge of the photo (Y = 0) [optional]
 */
@property(nonatomic) NSNumber* locationY;
/* Width of the license plate's location in pixels [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height of the license plate's location in pixels [optional]
 */
@property(nonatomic) NSNumber* height;
/* Confidence score on a range of 0.0 - 1.0 of the accuracy of the detected license plate, with higher scores being better; values about 0.75 are high confidence [optional]
 */
@property(nonatomic) NSNumber* licensePlateRecognitionConfidenceLevel;

@end
