#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDrawRectangleInstance.h"
@protocol CMDrawRectangleInstance;
@class CMDrawRectangleInstance;



@protocol CMDrawRectangleRequest
@end

@interface CMDrawRectangleRequest : CMObject

/* Image to draw rectangles on, in bytes.  You can also use the BaseImageUrl instead to supply image input as a URL [optional]
 */
@property(nonatomic) NSData* baseImageBytes;
/* Image to draw rectangles on, as an HTTP or HTTPS fully-qualified URL [optional]
 */
@property(nonatomic) NSString* baseImageUrl;
/* Rectangles to draw on the image.  Rectangles are drawn in index order. [optional]
 */
@property(nonatomic) NSArray<CMDrawRectangleInstance>* rectanglesToDraw;

@end
