#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDrawTextInstance.h"
@protocol CMDrawTextInstance;
@class CMDrawTextInstance;



@protocol CMDrawTextRequest
@end

@interface CMDrawTextRequest : CMObject

/* Image to draw text on, in bytes.  You can also use the BaseImageUrl instead to supply image input as a URL [optional]
 */
@property(nonatomic) NSData* baseImageBytes;
/* Image to draw text on, as an HTTP or HTTPS fully-qualified URL [optional]
 */
@property(nonatomic) NSString* baseImageUrl;
/* One or more pieces of text to draw onto the image [optional]
 */
@property(nonatomic) NSArray<CMDrawTextInstance>* textToDraw;

@end
