#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDrawTextInstance
@end

@interface CMDrawTextInstance : CMObject

/* Text string to draw [optional]
 */
@property(nonatomic) NSString* text;
/* Font Family to use.  Leave blank to default to \"Arial\".  Supported fonts including Arial, Calibri, Cambria, Candara, Consolas, Constantia, Corbel, Courier New, Courier Regular, Georgia, Impact Regular, Lucida, Modern Regular, Tahoma, Times New Roman, Verdana [optional]
 */
@property(nonatomic) NSString* fontFamilyName;
/* Font size to use. [optional]
 */
@property(nonatomic) NSNumber* fontSize;
/* Color to use - can be a hex value (with #) or HTML common color name [optional]
 */
@property(nonatomic) NSString* color;
/* Pixel location of the left edge of the text location [optional]
 */
@property(nonatomic) NSNumber* X;
/* Pixel location of the top edge of the text location [optional]
 */
@property(nonatomic) NSNumber* Y;
/* Width in pixels of the text box to draw the text in; text will wrap inside this box [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height in pixels of the text box to draw the text in; text will wrap inside this box [optional]
 */
@property(nonatomic) NSNumber* height;

@end
