#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFace
@end

@interface CMFace : CMObject

/* X coordinate of the left side of the face [optional]
 */
@property(nonatomic) NSNumber* leftX;
/* Y coordinate of the top side of the face [optional]
 */
@property(nonatomic) NSNumber* topY;
/* X coordinate of the right side of the face [optional]
 */
@property(nonatomic) NSNumber* rightX;
/* Y coordinate of the bottom side of the face [optional]
 */
@property(nonatomic) NSNumber* bottomY;

@end
