#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFaceMatch.h"
@protocol CMFaceMatch;
@class CMFaceMatch;



@protocol CMFaceCompareResponse
@end

@interface CMFaceCompareResponse : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Array of faces found in the input image [optional]
 */
@property(nonatomic) NSArray<CMFaceMatch>* faces;
/* Number of faces found in the image [optional]
 */
@property(nonatomic) NSNumber* faceCount;
/* Details of any errors that occurred [optional]
 */
@property(nonatomic) NSString* errorDetails;

@end
