#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFacePoint.h"
@protocol CMFacePoint;
@class CMFacePoint;



@protocol CMFaceWithLandmarks
@end

@interface CMFaceWithLandmarks : CMObject


@property(nonatomic) NSArray<CMFacePoint>* leftEyebrow;

@property(nonatomic) NSArray<CMFacePoint>* rightEyebrow;

@property(nonatomic) NSArray<CMFacePoint>* leftEye;

@property(nonatomic) NSArray<CMFacePoint>* rightEye;

@property(nonatomic) NSArray<CMFacePoint>* bottomAndSidesOfFace;

@property(nonatomic) NSArray<CMFacePoint>* noseBridge;

@property(nonatomic) NSArray<CMFacePoint>* noseBottom;

@property(nonatomic) NSArray<CMFacePoint>* lipsInnerOutline;

@property(nonatomic) NSArray<CMFacePoint>* lipsOuterOutline;
/* X coordinate of the left side of the face [optional]
 */
@property(nonatomic) NSNumber* leftX;
/* Y coordinate of the top side of the face [optional]
 */
@property(nonatomic) NSNumber* topY;
/* X coordinate of the right side of the face [optional]
 */
@property(nonatomic) NSNumber* rightX;
/* Y coordinate of the bottom side of the face [optional]
 */
@property(nonatomic) NSNumber* bottomY;

@end
