#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFacePoint
@end

@interface CMFacePoint : CMObject

/* X location, where 0 is the left-most pixel [optional]
 */
@property(nonatomic) NSNumber* X;
/* Y location, where 0 is the top-most pixel [optional]
 */
@property(nonatomic) NSNumber* Y;

@end
