#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFacePoint.h"
@protocol CMFacePoint;
@class CMFacePoint;



@protocol CMFaceWithLandmarks
@end

@interface CMFaceWithLandmarks : CMObject

/* X coordinate of the left side of the face [optional]
 */
@property(nonatomic) NSNumber* leftX;
/* Y coordinate of the top side of the face [optional]
 */
@property(nonatomic) NSNumber* topY;
/* X coordinate of the right side of the face [optional]
 */
@property(nonatomic) NSNumber* rightX;
/* Y coordinate of the bottom side of the face [optional]
 */
@property(nonatomic) NSNumber* bottomY;
/* Point locations of the left eyebrow (the eyebrow cloesest to the left side of the picture) [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* leftEyebrow;
/* Point locations of the right eyebrow (the eyebrow cloesest to the right side of the picture) [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* rightEyebrow;
/* Point locations of the left eye (the eye closest to the left side of the picture) [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* leftEye;
/* Point locations of the right eye (the eye closest to the right side of the picture) [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* rightEye;
/* Point locations of the bottom and sides of the face (cheeks and chin) [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* bottomAndSidesOfFace;
/* Point locations of the nose bridge (the vertical portion of the nose) [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* noseBridge;
/* Point locations of the bottom (nostrils) of the nose [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* noseBottom;
/* Point locations of the inner outline of the lips [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* lipsInnerOutline;
/* Point locations of the outer outline of the lips [optional]
 */
@property(nonatomic) NSArray<CMFacePoint>* lipsOuterOutline;

@end
