#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFineTextItem
@end

@interface CMFineTextItem : CMObject

/* X coordinate of the top/left text location; 0 represents the left edge of the input image [optional]
 */
@property(nonatomic) NSNumber* topLeftX;
/* Y coordinate of the top/left text location; 0 represents the top edge of the input image [optional]
 */
@property(nonatomic) NSNumber* topLeftY;
/* X coordinate of the top/right text location; 0 represents the left edge of the input image [optional]
 */
@property(nonatomic) NSNumber* topRightX;
/* Y coordinate of the top/right text location; 0 represents the top edge of the input image [optional]
 */
@property(nonatomic) NSNumber* topRightY;
/* X coordinate of the bottom/left text location; 0 represents the left edge of the input image [optional]
 */
@property(nonatomic) NSNumber* bottomLeftX;
/* Y coordinate of the bottom/left text location; 0 represents the top edge of the input image [optional]
 */
@property(nonatomic) NSNumber* bottomLeftY;
/* X coordinate of the bottom/right text location; 0 represents the left edge of the input image [optional]
 */
@property(nonatomic) NSNumber* bottomRightX;
/* Y coordinate of the bottom/right text location; 0 represents the top edge of the input image [optional]
 */
@property(nonatomic) NSNumber* bottomRightY;
/* Width in pixels of the text [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height in pixels of the text [optional]
 */
@property(nonatomic) NSNumber* height;
/* Rotation Angle in radians of the text [optional]
 */
@property(nonatomic) NSNumber* angle;

@end
