#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFindSymbolResult
@end

@interface CMFindSymbolResult : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Score between 0.0 and 1.0 that measures how closely the symbol matched; scores above 0.2 are good [optional]
 */
@property(nonatomic) NSNumber* matchScore;
/* X location of the left edge of the found location in pixels [optional]
 */
@property(nonatomic) NSNumber* xLeft;
/* Y location of the top edge of the found location in pixels [optional]
 */
@property(nonatomic) NSNumber* yTop;
/* Width of the found location in pixels [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height of the found location in pixels [optional]
 */
@property(nonatomic) NSNumber* height;

@end
