#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMImageSimilarityHashDistanceRequest
@end

@interface CMImageSimilarityHashDistanceRequest : CMObject

/* Image hash computed using Cloudmersive Image Hashing API [optional]
 */
@property(nonatomic) NSString* imageHash1;
/* Image hash computed using Cloudmersive Image Hashing API [optional]
 */
@property(nonatomic) NSString* imageHash2;

@end
