#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMImageSimilarityHashResponse
@end

@interface CMImageSimilarityHashResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* String representing image perceptual hash value; values with smaller Hamming Distances are more similar than ones with large Hamming Distances [optional]
 */
@property(nonatomic) NSString* imageHash;

@end
