#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMImageAiDetectionResult
@end

@interface CMImageAiDetectionResult : CMObject

/* True if the image is clean (not AI generated) and false otherwise [optional]
 */
@property(nonatomic) NSNumber* cleanResult;
/* Risk score between 0.0 (no risk) and 1.0 (highest risk), with anything over 0.8 being high risk [optional]
 */
@property(nonatomic) NSNumber* aiGeneratedRiskScore;
/* Tool used to generate the image, if identified (this cannot always be identified) [optional]
 */
@property(nonatomic) NSString* aiSource;

@end
