#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMRecognitionOutcome.h"
@protocol CMRecognitionOutcome;
@class CMRecognitionOutcome;



@protocol CMImageDescriptionResponse
@end

@interface CMImageDescriptionResponse : CMObject

/* Was the image processed successfully? [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Is the resulting best outcome recognition a high confidence outcome? [optional]
 */
@property(nonatomic) NSNumber* highconfidence;
/* The best Machine Learning outcome [optional]
 */
@property(nonatomic) CMRecognitionOutcome* bestOutcome;
/* Best backup (\"runner up\") Machine Learning outcome [optional]
 */
@property(nonatomic) CMRecognitionOutcome* runnerUpOutcome;

@end
