#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMNsfwResult
@end

@interface CMNsfwResult : CMObject

/* True if the classification was successfully run, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Score between 0.0 and 1.0.  Scores of 0.0-0.2 represent high probability safe content, while scores 0.8-1.0 represent high probability unsafe content.  Content between 0.2 and 0.8 is of increasing raciness. [optional]
 */
@property(nonatomic) NSNumber* score;
/* Classification result into four categories: SafeContent_HighProbability, UnsafeContent_HighProbability, RacyContent, SafeContent_ModerateProbability [optional]
 */
@property(nonatomic) NSString* classificationOutcome;

@end
