#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDetectedObject.h"
@protocol CMDetectedObject;
@class CMDetectedObject;



@protocol CMObjectDetectionResult
@end

@interface CMObjectDetectionResult : CMObject

/* Was the image processed successfully? [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Array of objects detected in the scene [optional]
 */
@property(nonatomic) NSArray<CMDetectedObject>* objects;
/* Number of objects detected in the scene [optional]
 */
@property(nonatomic) NSNumber* objectCount;

@end
