#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFace.h"
@protocol CMFace;
@class CMFace;



@protocol CMPersonWithGender
@end

@interface CMPersonWithGender : CMObject

/* Location and other information about the person's face corresponding to this age classification [optional]
 */
@property(nonatomic) CMFace* faceLocation;
/* Confidence level of gender classification; possible values are between 0.0 and 1.0; higher is better, with values &gt; 0.50 being high confidence results [optional]
 */
@property(nonatomic) NSNumber* genderClassificationConfidence;
/* The person's identified gender; possible values are \"Male\", \"Female\" and \"Unknown\" [optional]
 */
@property(nonatomic) NSString* genderClass;

@end
