#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMTextItem
@end

@interface CMTextItem : CMObject

/* Text detected in the image [optional]
 */
@property(nonatomic) NSString* detectedText;
/* Left X coordinate of the text location; 0 represents the left edge of the input image [optional]
 */
@property(nonatomic) NSNumber* leftX;
/* Top Y coordinate of the text location; 0 represents the top edge of the input image [optional]
 */
@property(nonatomic) NSNumber* topY;
/* Width in pixels of the text item [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height in pixels of the text item [optional]
 */
@property(nonatomic) NSNumber* height;

@end
