#import <Foundation/Foundation.h>
#import "CMImageAiDetectionResult.h"
#import "CMApi.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMAiImageDetectionApi: NSObject <CMApi>

extern NSString* kCMAiImageDetectionApiErrorDomain;
extern NSInteger kCMAiImageDetectionApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Detect if an input image was generated using AI
/// Detects if the input image was generated using AI tools.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return CMImageAiDetectionResult*
-(NSURLSessionTask*) aiImageDetectionDetectFileWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(CMImageAiDetectionResult* output, NSError* error)) handler;



@end
