#import <Foundation/Foundation.h>
#import "CMDrawPolygonRequest.h"
#import "CMDrawRectangleRequest.h"
#import "CMDrawTextRequest.h"
#import "CMApi.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMEditApi: NSObject <CMApi>

extern NSString* kCMEditApiErrorDomain;
extern NSInteger kCMEditApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Normalizes image rotation and removes EXIF rotation data
/// Automatically orients the input image based on EXIF information and then removes the EXIF information.  EXIF is an additional set of information stored in some images taken with cell phone cameras based on the orientation of the camera.  By normalizing rotation and removing EXIF data these images become much easier to process.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editAutoOrientWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Composite two images together
/// Composites two input images together; a layered image onto a base image.  The first image you input is the base image.  The second image (the layered image) will be composited on top of this base image.  Supports PNG transparency.  To control padding you can include transparent pixels at the border(s) of your layered images as appropriate.
///
/// @param location Location to composite the layered images; possible values are: \&quot;center\&quot;, \&quot;top-left\&quot;, \&quot;top-center\&quot;, \&quot;top-right\&quot;, \&quot;center-left\&quot;, \&quot;center-right\&quot;, \&quot;bottom-left\&quot;, \&quot;bottom-center\&quot;, \&quot;bottom-right\&quot;
/// @param baseImage Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// @param layeredImage Image to layer on top of the base image.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editCompositeBasicWithLocation: (NSString*) location
    baseImage: (NSURL*) baseImage
    layeredImage: (NSURL*) layeredImage
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Composite two images together precisely
/// Composites two input images together; a layered image onto a base image. Position is based on distance in pixels from each side.  The first image you input is the base image.  The second image (the layered image) will be composited on top of this base image.  Supports PNG transparency.  To control padding you can include transparent pixels at the border(s) of your layered images as appropriate.  Providing multiple parameters in a single axis (for example top and bottom) is not recommended, since only one of the parameters will be used per axis.
///
/// @param baseImage Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// @param layeredImage Image to layer on top of the base image.
/// @param top Optional; Desired distance in pixels from the top of the base image to the top of the layered image. (optional)
/// @param bottom Optional; Desired distance in pixels from the bottom of the base image to the bottom of the layered image. (optional)
/// @param left Optional; Desired distance in pixels from the left side of the base image to the left side of the layered image. (optional)
/// @param right Optional; Desired distance in pixels from the right side of the base image to the right side of the layered image. (optional)
/// @param width Optional; Desired width of the layered image in pixels. Leave height empty or 0 to automatically scale the image proportionally. (optional)
/// @param height Optional; Desired height of the layered image in pixels. Leave width empty or 0 to automatically scale the image proportionally. (optional)
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editCompositePreciseWithBaseImage: (NSURL*) baseImage
    layeredImage: (NSURL*) layeredImage
    top: (NSNumber*) top
    bottom: (NSNumber*) bottom
    left: (NSNumber*) left
    right: (NSNumber*) right
    width: (NSNumber*) width
    height: (NSNumber*) height
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Adaptively adjust the contrast of the image to be more appealing and easy to see
/// Uses Gamma to adjust the contrast adaptively the way the human eye sees the world.  Results significantly improve the viewability and visual appeal of the image.
///
/// @param gamma Gamma value to adjust the contrast in the image.  Recommended value is 2.0.  Values between 0.0 and 1.0 will reduce contrast, while values above 1.0 will increase contrast.
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editContrastAdaptiveWithGamma: (NSNumber*) gamma
    imageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Crop an image to an circular area
/// Crop an image to a target circular area
///
/// @param left The left edge of the circular crop area in pixels (X).
/// @param top The top edge of the circular crop area in pixels (Y).
/// @param radius The radius of the circular crop area in pixels.
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editCropCircleWithLeft: (NSNumber*) left
    top: (NSNumber*) top
    radius: (NSNumber*) radius
    imageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Crop an image to a rectangular area
/// Crop an image to a target rectangular area
///
/// @param left The left edge of the rectangular crop area in pixels (X).
/// @param top The top edge of the rectangular crop area in pixels (Y).
/// @param width The width of the rectangular crop area in pixels.
/// @param height The height of the rectangular crop area in pixels.
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editCropRectangleWithLeft: (NSNumber*) left
    top: (NSNumber*) top
    width: (NSNumber*) width
    height: (NSNumber*) height
    imageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Draw a polygon onto an image
/// Draw one or more polygons, with customized visuals, onto an image
///
/// @param request Polygon drawing request parameters
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editDrawPolygonWithRequest: (CMDrawPolygonRequest*) request
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Draw a rectangle onto an image
/// Draw one or more rectangles, with customized visuals, onto an image
///
/// @param request Draw rectangle parameters
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editDrawRectangleWithRequest: (CMDrawRectangleRequest*) request
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Draw text onto an image
/// Draw one or more pieces of text, with customized visuals, onto an image
///
/// @param request Draw text parameters
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editDrawTextWithRequest: (CMDrawTextRequest*) request
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Add a customizeable drop shadow to an image
/// Add a customizeable drop shadow to the image
///
/// @param X Horizontal (X) offset of the drop shadow
/// @param Y Vertical (Y) offset of the drop shadow
/// @param sigma Sigma (blur distance) of the drop shadow
/// @param opacity Opacity of the drop shadow; 0 is 0% and 100 is 100%
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editDropShadowWithX: (NSNumber*) X
    Y: (NSNumber*) Y
    sigma: (NSNumber*) sigma
    opacity: (NSNumber*) opacity
    imageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Invert, negate the colors in the image
/// Inverts (negates) all of the colors in the image.  If the image contains transparency, the transparency will first be removed prior to inverting the image.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editInvertWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Remove EXIF data from the image
/// Removes any EXIF data and profiles .
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editRemoveExifDataWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Remove transparency from the image
/// Removes any active transparency in the image.  Effectively renders the image at the same resolution, in the same file format, over a white background, thus removing transparency.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editRemoveTransparencyWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Rotate an image any number of degrees
/// Rotates an image by an arbitrary number of degrees
///
/// @param degrees Degrees to rotate the image; values range from 0.0 to 360.0.
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) editRotateWithDegrees: (NSNumber*) degrees
    imageFile: (NSURL*) imageFile
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;



@end
