#import <Foundation/Foundation.h>
#import "CMDominantColorResult.h"
#import "CMImageMetadata.h"
#import "CMApi.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMInfoApi: NSObject <CMApi>

extern NSString* kCMInfoApiErrorDomain;
extern NSInteger kCMInfoApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Returns the dominant colors of the image
/// Uses advanced image processing to extract the top 5 dominant colors in the image, returned in the order of dominance with the most-dominant color first.  These are the primary perceptual colors used in the image as perceived by a viewer.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return CMDominantColorResult*
-(NSURLSessionTask*) infoGetDominantColorWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(CMDominantColorResult* output, NSError* error)) handler;


/// Returns the image metadata including EXIF and resolution
/// Returns the metadata information on the image, including file type, EXIF (if available), and resolution.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return CMImageMetadata*
-(NSURLSessionTask*) infoGetMetadataWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(CMImageMetadata* output, NSError* error)) handler;



@end
