#import <Foundation/Foundation.h>
#import "CMNsfwResult.h"
#import "CMApi.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMNsfwApi: NSObject <CMApi>

extern NSString* kCMNsfwApiErrorDomain;
extern NSInteger kCMNsfwApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Not safe for work NSFW racy content classification
/// Classify an image into Not Safe For Work (NSFW)/Porn/Racy content and Safe Content.
///
/// @param imageFile Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
/// 
///  code:200 message:"OK"
///
/// @return CMNsfwResult*
-(NSURLSessionTask*) nsfwClassifyWithImageFile: (NSURL*) imageFile
    completionHandler: (void (^)(CMNsfwResult* output, NSError* error)) handler;



@end
