#import <Foundation/Foundation.h>
#import "CMCreateHandwritingRequest.h"
#import "CMApi.h"

/**
* imageapi
* Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMTextGenerationApi: NSObject <CMApi>

extern NSString* kCMTextGenerationApiErrorDomain;
extern NSInteger kCMTextGenerationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create an image of handwriting in PNG format
/// Uses Deep Learning to generate realistic handwriting and returns the result as a PNG image
///
/// @param request Draw text parameters
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) textGenerationCreateHandwritingPngWithRequest: (CMCreateHandwritingRequest*) request
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;



@end
